on:
  pull_request:
    branches:
      - main
    types: [closed]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup git config for bot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set release notes
        id: release_notes
        run: |
            echo "RELEASE_TAG=$(echo ${github.ref} | grep -o  '[^/]\+$')" >> $GITHUB_ENV
            echo "RELEASE_NOTES=$(git log --pretty="- %s")" >> $GITHUB_ENV

      - name: Post Release notes
        run: |
          echo "${{ env.RELEASE_TAG }}"
          echo "${{ env.RELEASE_NOTES }}"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: 1.2.4
      #     release_name: Release 125
      #     body: ${{ env.RELEASE_NOTES }}
      #     draft: false
      #     prerelease: false