on:
  pull_request:
    branches:
    - main
    types: [closed]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup git config for bot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set release tag
        id: release_tag
        run: |
            echo "RELEASE_TAG=$(echo ${{ github.head.ref }} | grep -o  '[^/]\+$')" >> $GITHUB_ENV

      - name: Set release notes
        id: release_notes
        run: |
            git fetch
            echo "RELEASE_NOTES=$(git log origin/${{ github.event.pull_request.head.ref }}.. --pretty="- %s")" >> $GITHUB_ENV

      - name: Post Release notes
        run: |
          echo "${{ env.RELEASE_TAG }}"
          echo "${{ env.RELEASE_NOTES }}"
          echo "${{ toJSON(github) }}"
          git log main --pretty="- %s

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false