on:
  push:
   branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Set release notes
        id: release_notes
        run: |
            echo "RELEASE_NOTES=$(git log --pretty="- %s")" >> $GITHUB_ENV
      - name: Post Release notes
        run: |
          echo "${{ env.RELEASE_NOTES }}"
